## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agones-openmatch-director
  name: agones-openmatch-director
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agones-openmatch-director
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: agones-openmatch-director
    spec:
      containers:
      
      - args:
        - /app/director
        - -backendAddr
        - $(OPENMATCH_BACKEND_ADDR)
        - -backendPort
        - $(OPENMATCH_BACKEND_PORT)
        - -functionAddr
        - $(OPENMATCH_MATCH_FUNCTION_ADDR)
        - -functionPort
        - $(OPENMATCH_MATCH_FUNCTION_PORT)
        - -allocatorAddr
        - $(AGONES_ALLOCATOR_ADDR)
        - -allocatorPort
        - $(AGONES_ALLOCATOR_PORT)
        - -certFile
        - $(CRT_FILE)
        - -keyFile
        - $(KEY_FILE)
        - -caFile
        - $(CA_FILE)
        - -namespace
        - $(NAMESPACE)
        - -multicluster
        - -regions 
        - $(REGIONS)
        - -ranges 
        - $(RANGES)
        - -interval
        - $(INTERVAL)
        
        env:
        - name: OPENMATCH_BACKEND_ADDR
          value: open-match-backend.open-match.svc.cluster.local
        - name: OPENMATCH_BACKEND_PORT
          value: "50505"
        - name: OPENMATCH_MATCH_FUNCTION_ADDR
          value: agones-openmatch-mmf.agones-openmatch.svc.cluster.local
        - name: OPENMATCH_MATCH_FUNCTION_PORT
          value: "50502"
        - name: AGONES_ALLOCATOR_ADDR
          value: agones-allocator.agones-system.svc.cluster.local
        - name: AGONES_ALLOCATOR_PORT
          value: "443"
        - name: CRT_FILE
          value: tls.crt
        - name: KEY_FILE
          value: tls.key
        - name: CA_FILE
          value: ca.crt
        - name: NAMESPACE
          value: agones-system
        - name: REGIONS
          value: ${REGION1},${REGION2}
        - name: RANGES
          value: 0-24,25-49,50-74,74-99,100-9999
        - name: INTERVAL
          value: "5"

        image: ${REGISTRY}/agones-openmatch-director
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        name: director
        resources:
          limits:
            cpu: "1"
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/agones-tls
          name: agones-tls-volume
        - mountPath: /app/openmatch-tls
          name: openmatch-tls-volume
        - mountPath: /app/global-accelerator-mapping
          name: global-accelerator-mapping
      hostname: agones-openmatch-director
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                - key: openmatch
                  operator: In
                  values:
                  - customization
      volumes:
      - configMap:
          defaultMode: 420
          name: allocator-tls
        name: agones-tls-volume
      - secret:
          defaultMode: 420
          secretName: open-match-tls-certmanager
        name: openmatch-tls-volume
      - configMap:
          defaultMode: 420
          name: global-accelerator-mapping
        name: global-accelerator-mapping

